### ISSUE TITLE
途中で400エラーがAPIから返され、落ちる

### ISSUE THREAD

**Issue by 1grc** [1grc/esa_article_import#3]
- タイトルに `[hoge]` が含まれている時、落ちる？
→検証予定

**Comment by 1grc** [comment]
単純に存在しないメンバーのとき400になっているだけだった
→対処方法：とりあえずcase追加

**Comment by 1grc** [comment]
case追加後、posts/66の記事で落ちる
以下ログ
400 Bad Request: param is missing or the value is empty: post
Traceback (most recent call last):
	6: from sample.rb:143:in `<main>'
	5: from sample.rb:98:in `import'
	4: from sample.rb:103:in `import'
	3: from sample.rb:103:in `each'
	2: from sample.rb:104:in `block in import'
	1: from sample.rb:121:in `create'
sample.rb:121:in `[]=': no implicit conversion of Symbol into Integer (TypeError)

**Comment by 1grc** [comment]
途中で型が配列になってたので直してdone.
